x-common-php-config: &common-php-config
  image: 'notifreak-php'
  restart: 'unless-stopped'

  volumes:
    - 'caddy_data:/data'
    - 'caddy_config:/config'

services:
  php:
    <<: *common-php-config

    ports:
      - target: 80
        published: '${HTTP_PORT:-80}'
        protocol: 'tcp'

      - target: 443
        published: '${HTTPS_PORT:-443}'
        protocol: 'tcp'

      - target: 443
        published: '${HTTP3_PORT:-443}'
        protocol: 'udp'

  worker-messenger:
    <<: *common-php-config
    command: 'php ./bin/console messenger:consume -vv --limit=10 --memory-limit=128M --time-limit=3600'

    depends_on:
      php:
        condition: service_healthy
        restart: true

volumes:
  caddy_data:
  caddy_config:
