x-common-php-config: &common-php-config
  build:
    context: '.'
    dockerfile: '.docker/Dockerfile'
    target: 'frankenphp_prod'

  environment:
    SERVER_NAME: '${SERVER_NAME:-localhost}, php:80'
    APP_SECRET: '${APP_SECRET}'
    APP_TIMEZONE: '${APP_TIMEZONE}'
    APP_LOCALE: '${APP_LOCALE}'
    APP_URI: '${APP_URI}'
    SECURITY_KEY: '${SECURITY_KEY}'
    MESSENGER_TRANSPORT_DSN: '${MESSENGER_TRANSPORT_DSN}'
    TELEGRAM_DSN: '${TELEGRAM_DSN}'

services:
  worker-messenger:
    <<: *common-php-config

  php:
    <<: *common-php-config
